{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "namespace": "video-utils",
  "resources": [
    "namespace.json",
    "configmap.json",
    "pvc.json",
    "deployment.json",
    "service.json",
    "networkpolicy.json"
  ]
}
