"use strict";
const byId = id => document.getElementById(id);
let session = null, store = null, activeRole = null, selectedId = null, editId = null;
const players = new Map();
const titles = {video:"Processed video", original:"Original audition", clean:"Clean audition", residual:"Removed signal"};
function human(value){return String(value).replaceAll("_"," ");}
function clock(value){const sign=value<0?"−":"";value=Math.abs(value);return sign+String(Math.floor(value/60)).padStart(2,"0")+":"+(value%60).toFixed(3).padStart(6,"0");}
function notice(text,error=false){byId("notice").textContent=text;byId("notice").classList.toggle("error",error);}
function node(tag,text,cls){const item=document.createElement(tag);if(text!==undefined)item.textContent=text;if(cls)item.className=cls;return item;}
function currentSource(){const player=players.get(activeRole);return (player?player.currentTime:0)+(activeRole==="video"?session.timeline.format_start_seconds:session.timeline.audio_start_seconds);}
function setRole(role){activeRole=role;for(const [key,player] of players){player.hidden=key!==role;if(key!==role)player.pause();}for(const tab of byId("player-tabs").children)tab.setAttribute("aria-pressed",String(tab.dataset.role===role));updatePosition();}
function seekSource(source){source=Math.max(session.timeline.source_min_seconds,Math.min(source,session.timeline.source_max_seconds));for(const [role,player] of players){const relative=Math.max(0,source-(role==="video"?session.timeline.format_start_seconds:session.timeline.audio_start_seconds));const apply=()=>{try{player.currentTime=Number.isFinite(player.duration)?Math.min(relative,player.duration):relative;}catch(_){notice("This player cannot seek here yet. Use its playback controls.",true);}};if(player.readyState<1){player.addEventListener("loadedmetadata",apply,{once:true});player.load();}else apply();}byId("position").value=source;byId("source-position").textContent=clock(source);}
function updatePosition(){if(!session)return;const source=currentSource();byId("position").value=source;byId("source-position").textContent=clock(source);const start=Number(byId("note-start").value),end=Number(byId("note-end").value);const player=players.get(activeRole);if(byId("loop-span").checked&&player&&!player.paused&&end>start&&source>=end)seekSource(start);}
function renderPlayers(){for(const role of ["video","original","clean","residual"]){if(!session.media[role])continue;const player=node(role==="video"?"video":"audio");player.className="player";player.controls=true;player.preload="none";if(role==="video")player.playsInline=true;player.src=session.media[role];player.addEventListener("timeupdate",updatePosition);player.addEventListener("play",()=>{setRole(role);for(const [other,value] of players)if(other!==role)value.pause();});byId("players").append(player);players.set(role,player);const tab=node("button",titles[role]);tab.type="button";tab.dataset.role=role;tab.setAttribute("aria-pressed","false");tab.addEventListener("click",()=>{const source=currentSource();setRole(role);seekSource(source);});byId("player-tabs").append(tab);}if(players.size)setRole(players.has("video")?"video":players.has("clean")?"clean":"original");else byId("players").append(node("p","No verified playable media is available in this run.","empty"));}
function filterOptions(){for(const [target,key] of [["kind-filter","kind"],["confidence-filter","confidence"]]){const values=[...new Set(session.markers.map(item=>item[key]))].sort();for(const value of values){const option=node("option",human(value));option.value=value;byId(target).append(option);}byId(target).addEventListener("change",renderMarkers);}}
function selectMarker(item){selectedId=item.id;editId=null;byId("note-start").value=item.source_start_seconds.toFixed(3);byId("note-end").value=item.source_end_seconds.toFixed(3);byId("note-category").value=/phrase|riff|recurrence|region|bar|breakdown/.test(item.kind)?"phrase":"rhythm";byId("note-status").value="needs_review";byId("selected-proposal").textContent="Selected proposal: "+human(item.kind);seekSource(item.source_start_seconds);renderMarkers();}
function renderMarkers(){const kind=byId("kind-filter").value,confidence=byId("confidence-filter").value;const items=session.markers.filter(item=>(!kind||item.kind===kind)&&(!confidence||item.confidence===confidence));byId("candidate-count").textContent=items.length+" / "+session.markers.length;const list=byId("candidates");list.replaceChildren();const track=byId("marker-track");track.replaceChildren();if(!items.length)list.append(node("p","No proposals match these filters. You can still mark your own listening span.","empty"));for(const item of items){const button=node("button",undefined,"candidate"+(item.id===selectedId?" selected":""));button.type="button";button.append(node("span",clock(item.source_start_seconds)+" → "+clock(item.source_end_seconds),"time"),node("span",human(item.kind),"kind"),node("small",human(item.confidence)+" · "+human(item.status)));button.addEventListener("click",()=>selectMarker(item));list.append(button);}const duration=session.timeline.source_max_seconds-session.timeline.source_min_seconds;for(const item of items.slice(0,1000)){const mark=node("button",undefined,"track-mark"+(item.id===selectedId?" selected":""));mark.type="button";mark.style.left=100*(item.source_start_seconds-session.timeline.source_min_seconds)/duration+"%";mark.style.width=Math.max(.2,100*(item.source_end_seconds-item.source_start_seconds)/duration)+"%";mark.title=human(item.kind)+" · "+clock(item.source_start_seconds);mark.setAttribute("aria-label",mark.title);mark.addEventListener("click",()=>selectMarker(item));track.append(mark);}}
function renderNotes(){const target=byId("saved-notes");target.replaceChildren();if(!store.annotations.length)target.append(node("p","Your listening notes will appear here and remain available when you reopen this run.","empty"));for(const item of store.annotations){const article=node("article",undefined,"saved-note");article.append(node("h3",clock(item.source_start_seconds)+" → "+clock(item.source_end_seconds)),node("p",item.note),node("p",human(item.category)+" · "+human(item.status)+" · "+item.updated_at,"meta"));const seek=node("button","Seek span","quiet");seek.type="button";seek.addEventListener("click",()=>seekSource(item.source_start_seconds));const edit=node("button","Edit note","quiet");edit.type="button";edit.addEventListener("click",()=>{editId=item.id;selectedId=item.candidate_id;byId("note-start").value=item.source_start_seconds.toFixed(3);byId("note-end").value=item.source_end_seconds.toFixed(3);byId("note-category").value=item.category;byId("note-status").value=item.status;byId("note-text").value=item.note;byId("selected-proposal").textContent="Editing a saved listening note.";renderMarkers();byId("note-text").focus();});article.append(seek,document.createTextNode(" "),edit);target.append(article);}}
async function refreshNotes(){const response=await fetch("/api/annotations",{cache:"no-store"});const value=await response.json();if(!response.ok)throw new Error(value.error||"notes_unavailable");store=value;renderNotes();}
function resetNote(){editId=null;selectedId=null;const time=currentSource();byId("note-start").value=time.toFixed(3);byId("note-end").value=time.toFixed(3);byId("note-category").value="phrase";byId("note-status").value="needs_review";byId("note-text").value="";byId("selected-proposal").textContent="Select a proposal or capture your own span.";renderMarkers();}
async function saveNote(event){event.preventDefault();const start=Number(byId("note-start").value),end=Number(byId("note-end").value);if(!Number.isFinite(start)||!Number.isFinite(end)||end<start){notice("Choose an ordered start and end for this span.",true);return;}const annotation={source_start_seconds:start,source_end_seconds:end,category:byId("note-category").value,status:byId("note-status").value,note:byId("note-text").value};if(editId)annotation.id=editId;if(selectedId)annotation.candidate_id=selectedId;const previousIds=new Set(store.annotations.map(item=>item.id));const submit=byId("annotation-form").querySelector("button[type=submit]");submit.disabled=true;try{const response=await fetch("/api/annotations",{method:"POST",headers:{"Content-Type":"application/json","X-Review-Token":session.token},body:JSON.stringify({expected_revision:store.revision,annotation})});const value=await response.json();if(!response.ok){if(value.error==="stale_annotation_revision"){await refreshNotes();throw new Error("Saved notes changed in another window. Review the refreshed notes, then save again.");}throw new Error(human(value.error||"Could not save this note."));}store=value;const saved=value.annotations.find(item=>editId?item.id===editId:!previousIds.has(item.id));if(saved)editId=saved.id;renderNotes();notice("Listening note saved for this recording.");}catch(error){notice(error.message,true);}finally{submit.disabled=false;}}
function downloadNotes(){const url=URL.createObjectURL(new Blob([JSON.stringify(store,null,2)+"\n"],{type:"application/json"}));const link=node("a");link.href=url;link.download="guitar-listening-notes.json";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function init(){try{const response=await fetch("/api/session",{cache:"no-store"});session=await response.json();if(!response.ok)throw new Error(human(session.error||"Session unavailable"));store=session.annotations;byId("source-name").textContent=session.source_name;let pulseContext="";if(session.declared_bpm&&session.metrical_interpretations?.length){const nearest=session.metrical_interpretations.reduce((best,item)=>Math.abs(item.bpm-session.declared_bpm)<Math.abs(best.bpm-session.declared_bpm)?item:best);if(Math.abs(nearest.bpm-session.fitted_bpm)>.01)pulseContext="Compatible pulse interpretation: "+nearest.bpm.toFixed(2)+" BPM (derived). ";}byId("tempo-context").textContent=(session.declared_bpm?"Declared tempo: "+session.declared_bpm+" BPM. ":"")+(session.fitted_bpm?"Fitted recording pulse: "+session.fitted_bpm.toFixed(2)+" BPM. ":"")+pulseContext+"Pulse subdivisions and section identities remain review candidates.";byId("identity").textContent="Original source SHA-256: "+session.source_sha256+". Listening acceptance remains separate.";for(const id of ["note-start","note-end","position"]){byId(id).min=session.timeline.source_min_seconds;byId(id).max=session.timeline.source_max_seconds;}renderPlayers();filterOptions();renderMarkers();renderNotes();resetNote();byId("position").addEventListener("input",event=>seekSource(Number(event.target.value)));byId("span-start").addEventListener("click",()=>{const start=currentSource();byId("note-start").value=start.toFixed(3);if(Number(byId("note-end").value)<start)byId("note-end").value=start.toFixed(3);});byId("span-end").addEventListener("click",()=>{const end=currentSource();byId("note-end").value=end.toFixed(3);if(Number(byId("note-start").value)>end)byId("note-start").value=end.toFixed(3);});byId("new-note").addEventListener("click",resetNote);byId("annotation-form").addEventListener("submit",saveNote);byId("refresh-notes").addEventListener("click",()=>refreshNotes().then(()=>notice("Saved notes refreshed.")).catch(error=>notice(error.message,true)));byId("download-notes").addEventListener("click",downloadNotes);notice("Ready for manual listening. Nothing plays automatically.");}catch(error){notice(error.message,true);}}
init();
