// Pure builder for the one admitted web job request (WEB_UI_S2.md sections 5 and 8). Server-only.
// No imports, no I/O, no randomness: importable by plain `node` (type stripping) so the parity
// fixtures under web/fixtures/parity/ are generated by this exact module.
//
// The BFF does NOT re-validate knob values: it forwards exactly the knobs the user set, with
// their JSON types unchanged, so the control API (WebJobs.normalize_parameters -> tool_api.validate)
// is the single validator. Only the request *shape* is checked here.

export const JOB_TOOL = 'share_export';
export const KNOB_KEYS = ['height', 'crf', 'audio_kbps', 'codec', 'timeout_seconds'] as const;
export const IDEMPOTENCY_KEY_PATTERN = /^ui-[0-9a-f]{32}$/;
export const SOURCE_ARTIFACT_ID_PATTERN = /^art_[0-9a-f]{32}$/;
export const MAX_PARAMETERS = 16;
const PARAMETER_NAME_PATTERN = /^[a-z_]{1,64}$/;
const MAX_STRING_VALUE = 64;

export type JsonScalar = string | number | boolean;

export interface JobRequestBody {
	readonly tool: 'share_export';
	readonly source_artifact_id: string;
	readonly parameters: Readonly<Record<string, JsonScalar>>;
	readonly idempotency_key: string;
}

export type JobRequestRefusal = 'invalid_source_id' | 'invalid_idempotency_key' | 'invalid_parameters_shape';

export type JobRequestResult =
	| { readonly ok: true; readonly body: JobRequestBody }
	| { readonly ok: false; readonly code: JobRequestRefusal };

function isPlainObject(value: unknown): value is Record<string, unknown> {
	if (typeof value !== 'object' || value === null || Array.isArray(value)) return false;
	const proto = Object.getPrototypeOf(value);
	return proto === Object.prototype || proto === null;
}

function isScalar(value: unknown): value is JsonScalar {
	if (typeof value === 'boolean') return true;
	if (typeof value === 'number') return Number.isFinite(value);
	return typeof value === 'string' && value.length <= MAX_STRING_VALUE;
}

/**
 * Build `{tool, source_artifact_id, parameters, idempotency_key}` from the user's form state.
 * `parameters` holds only knobs the user set (an omitted knob takes the descriptor default
 * upstream). Values keep their JSON type: `27.5`, `true` or `"27"` are forwarded unchanged and
 * refused by the control API with `invalid_parameters`, exactly as the CLI/MCP validator refuses them.
 */
export function buildJobRequest(input: {
	readonly sourceArtifactId: unknown;
	readonly parameters: unknown;
	readonly idempotencyKey: unknown;
}): JobRequestResult {
	const { sourceArtifactId, parameters, idempotencyKey } = input;
	if (typeof sourceArtifactId !== 'string' || !SOURCE_ARTIFACT_ID_PATTERN.test(sourceArtifactId)) {
		return { ok: false, code: 'invalid_source_id' };
	}
	if (typeof idempotencyKey !== 'string' || !IDEMPOTENCY_KEY_PATTERN.test(idempotencyKey)) {
		return { ok: false, code: 'invalid_idempotency_key' };
	}
	const raw = parameters === undefined ? {} : parameters;
	if (!isPlainObject(raw)) return { ok: false, code: 'invalid_parameters_shape' };
	const keys = Object.keys(raw);
	if (keys.length > MAX_PARAMETERS) return { ok: false, code: 'invalid_parameters_shape' };
	const forwarded: Record<string, JsonScalar> = {};
	for (const key of keys) {
		const value = raw[key];
		if (!PARAMETER_NAME_PATTERN.test(key) || !isScalar(value)) {
			return { ok: false, code: 'invalid_parameters_shape' };
		}
		forwarded[key] = value;
	}
	return {
		ok: true,
		body: {
			tool: JOB_TOOL,
			source_artifact_id: sourceArtifactId,
			parameters: forwarded,
			idempotency_key: idempotencyKey
		}
	};
}
